---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: promlens
  namespace: promlens
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: promlens
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
