---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: telemetry
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki
    version: 0.29.0
  valuesFrom:
  - secretKeyRef:
      name: loki
