---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: telemetry
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~2
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki
    version: 2.0.2
  # valuesFrom:
  # - secretKeyRef:
  #     name: loki-helm-release
