apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: telemetry
spec:
  encryptedData:
    values.yaml: AgBIBQEULZICjtx+nWCGB3nNRODRwQ4sDY/79AGLbf+rnaKQYxh+4PD9d8dhAMPQtYXr3AHupzV0vZ2lDz2KDqoulATlnLZDPqDII/+8t6DkinRIMHD3K7x60PkxRuUfn7W6eNNlaG0O0xP3I3qOGFA0sfi1Cebm0cx6q+MVVHuCKFhZQHgZzk7aSy3E50qCuuRB+LeuRaqy+wlbH5OHFNOoMBfc8COEZQcEGxPxp7qCLasaZjkS5Ce7uqz4aMIg8iVS8A4cqAb00iL8vISumGJvJpnJCHM+kWJrV1jSdHZBhwBvF2vZTVZDO1bZDry25yLuUZZmLHCU6C0geBHGwkOeInL2XYeV+G5XWAbYE9ku/0yNN4AsEK/JfzwB9esngdDAYGNhCHwBYxb2Nta3Nd8zKkF9pXVdMelmhgZ4NZD50Er3XBCawRt2zjYTFRi51bFUtNuuRjRU/lMint1YM69Y1NREvYgkkoqxkT6m9CNhfL6+PzSgbeKn1XFauaUcuY+WMB+fjp9s6cIW2in40tvVVseBg4h1b9X1S4VaAR8wtwaJGonoP/puXkzJ2Wyn3c9ZBSdDLzuG/G8elv96XZxm4vlkYzDSJV8IK6fRNmQFGa3GyMxjGj8yACbxcJQ8FeQOeIGRNxbujaK3Wkx/NJhcR1CYxLbCoSl1J9uMDjwUlwptYFFk6RRCPS2SkCXyZuXO0v30gn0tJUnAZf49lDXq3PDgn9zCH+tRIPeyk250dAZNxxtN6NhraJjnpTC5bjaWYXaLyJCe4Ae8k6KcxMSaqQbY+3MqUW9wuCdAZuyZmUoS2s4T3r6z3CQ63lKnA09c5gF52DdJ/vNYw4X+iw+lNplqvU0JHT4YbdXALfK+GkjbJVTJchfZ8xEiKhj8aGXLl+a9wBX2bcitiZnVDETrjHOYx96AFKaHDMtzmzjXbvv7bwUTtbhEzFW35KCmyY9/W58As/DdwyBn++xhevrnutq8m72XYwkL6YFYgXwPbrCkUyvoffqwXHyI6shAqEjIz8uEJIhVOFJ6rH/cklqjYx4ardJnYc2qekD1q+Blta01wlESuNlBCj2rfpDHP3Maz5FkvNVHUMQ+K6b9u4KgqkHOY+Obh/X6lqUN5Ya7xCeOjpia44ql1G9mXxQ1ZsN8cvurf0ZfeWJHeJ6kFeVuc43QAbrMsJJ6+lIzGljxwSkzBXUrMGbNivo7n45Ez13meA9qjCHnwbq+Riy0kXNJlajsts/e/7nz/pr5MLVC783MG4PMwYzNmnZ3dIj7Ll1MHEm1TMToZENDgH+D6BbS8ioBVPrJS9SEt/Qm0Kivk4NBkQJK3tSAVFcA/xCaxByiQabOvcCSx/5vPKmoz+6hLUrzqtX/OOIu/gTAmLUP0tI0/4P4/IsktLovuT+HG0t6Y75MdMD9JALi0+yVTMH9dMtD+ux8mrqKNeaInCzjG1NC6uf0eDS5Gbx/1Zeo9ElSOH1NlkE9fyaii5diwDl0/fNNFfQSdJSAMdraajaJ9IliwJM=
  template:
    metadata:
      creationTimestamp: null
      name: loki
      namespace: telemetry

