---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki
  namespace: telemetry
spec:
  encryptedData:
    values.yaml: AgCGGWvLY3ZYzCHylT0kfzJtrK1L3yf7FJ4mYtT7avhay7uNPxuKHzOkYWNENBxM6zHOUopU/Nvjmd5Y3TKohLZJPLCjSkEcIZDKHVwspoZ17sNVPIW190fIcznr1eea91vib/RSI1QN++6khx7Fe00hJme/HrpNUSUFU+YRlioI+QOgQXNEKmhM1xWt0w1azcPZTvie/+q6ySCXyNPbDO0drGQLs5Br6LRiSx0qUgMmL0NSdZo4rnQmBZEDscyTzqU/9MpmHL/mGe7g48oZW4fTNw9gu/o+POhSoQQQG2W/iTYuQMa6EkHA02en1MPyShUbmi+6Umfc1lSWnIsD/UUhtnjizEcNk3e+pySCM3kZSJy/bEjjy/zCI2Ih5OGiiQuYaqJetkr1FqGF1W/mIxB/Hbwt1pvF+nQn0jC/6d+uawEBYwQxG6Llvzm6Ijd9BIc734tiSR0J34H+mtkdjTCkhtmq1XQnrFehTLLKCfjE/ITv0/Xq9Mv6AuvZFmaEMKJSglZGIXQXYnKPlcTbFc/xTKbpEfrTKpcZPKpgnRvtvJDQOoA7AwENbeuS0TFNDlV9jBYZnb322hyRJnxFT6e5HmiBw6mhHmXaf5cbZ3VhB+pw2BV/I3KFDHaIVEfBe9BiZ4I7BocQhAd+BzhirtroNueMAuZ1cWVOPHi83ALMGgU4eD1f5kp5xBTxAPwdtXx6esWujUkIK8SQSDGtJ0sI/yKvOaRh2IYs8kabFSyD06YcUAb/b188QPZXBIVS2NTZzrsWWQMN+bOD0+KoyM/9sk+WvnnADsjXmJY1yOe3WvCHKYD6CAdZJjp82+QP4vIubm4f1jvI9wEdQG3hxsRnqx9+7VN9ndfBjcOYaW8srXqGgpAWmnPiqfo1ni1G+ZzcSUphz8b6OcWXFtlucSEhUS2AO1MiHlhX7NFxljynRwx/N6TPuYDFcy0iUp/+WJFpl6m9REXE4wfdyoxSB7C06Ltwxu4ykEzP3TDQbK062VGqhJaErdspK+EAD6HQHyY/XS9VSfPdMTjXSyZKzCMjk0cw/MLwCfJHCpMLeiMIhM1qbhWcE1ne6J6NnArBYHCFgu4aoalFxB33u8LzoZg1IGLohPy2RfrzK9HyGEkVksIqUDgroy+iWU8EDC3Whl9tuGDrbRcxZIMUifXIrd6mpYQ8GTaZDZW6vpugFFAnS7vE3F+GDLv8ulEJJWpYY9QchciNSs3jr1ppZFH6ISIn5todJQ06lVF9d4CVF7IpOjldYCvTaJViT9XliKqoSToGP3x+afu9eGEHgsHh1J85pw/BY9u9bG1LKSTL+a5dVE5YUfUBKQlIYzRCwGk0TfRpSc4/f6g8x65R65QV15hlJaYYhsjZO4Uq6HBzjCwDGX34h9RzNS/iWg==
  template:
    metadata:
      name: loki
      namespace: telemetry
