apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: telemetry
spec:
  encryptedData:
    values.yaml: AgB7BvG9MHIe451efgd0OEnbrCy57EtNbfv4iAx9Rk5ky9AUe3dakoHw6epp3ZkdyBbb+o2AYj4ZZEGZdK4zy5J2jmkEQemKvyzX4rAOZyPMwEw/wjOuZ9C9i/cJsuAE9faduSEHG1VeTUC+QTTTsvSdYeuxhCodTjexaISVatCdROyF2as99PQzGoub2XTjs/6AoWZURlwVzMR8TNl51en7/dmkOppgAlGijjrL8tEAf1SQFjcxew2Li0Y0wvAXz69lBLJqbuWisizn77I2yDaABY9RMf5FSs2LDEaKAdRAKylirgFVZhvI/ZYYqQ/9f20v9jXN/mQaB3LQ9qsJhcWhSxmKN8ymQ/lRSvrQsl7rf3hGeDEj/i3XnFXsYpnxzDN39/YejOXcA5jLsVk0XGg0gBZG0oqV5iF/0IcpV7HLWZSPgswv3ax0vH+giukl1tqqZ/R+kGhc4VLynAXvepGL5OmUvUJluS6bcjFFJE9eS16tCe3SYkf9oYZUCq59031hav3lU5cA4bS8jFXbfMRjTfhrz3G25Pipswf7ZYTxoibADtteseoSDeFRUooWWpdxPjRNQJWBJLiNITx6F5CFBwSVR8llaxC58Hsq/xcmNDCKvN5Vit/4CREHvV9YpjReaN83jqZazJ01AzXabB4lHmRqXNlHREdfN1phlF/P4EJYlAlIjcpwVsfICtXkkI7TNq3NubC18E6pwjutzijS+cxlPtfTzKE6xEPVd3MtVrwAMTw1qnQuCESK994ZaSTpnassX9NbXZ+kBgsYyhNf+mlw5Y97j14N07WyZw6RBYiPjvG2dUKjv9mGehWvLX7wBsruqsH0R2Ps3uEloXX1YT3QpErdV+07Ew+Q5Pgjz7iX2fMTXjtwzQPQMN00aDr0M6Qmc3r4bWYDd0xF7DdyZ21Dxh5La8yA9AJ8jAhHeSLREQsu7XPVCtZBiMKohymAoklw9yA35hTnimvrHe7y/h5iJ7+GeRVhhLSfe6iWUAVuf2bLLgW7qeHbTORD9aO8tw3zkJh+SLVuqjWSvHkL4kPpGqLoGAOl33lGhA1QDbNGBCVMqr46B7MvN37Si/Vg+tJbId4JS2J8kNk3wlUEei9JjwZImWO5UMubmHR5dUZfO3YQAx8Mz3AT8Ce+9oUp0vW06GsO3tq5O1FwGlE+Pum0kTydg7RFtEkjOj4R4TEwURnIPIaJyOMeDB6iPPURbgPGjIBWt9L5iieWmxu6Adxso95XAY/WC8cTicyA5JJ3nKkdhJjmM8Ia+wCwaFv70LeLfkWKJGduiSby1cuXygA5atTaLPV/Db/XDwes8i3Av5+B5e1tXWO9tyUYnXE1rPm5Ty5MUuvQNmJy2IjhSFeky/60OtVNBAZIUGfkHcMrtsJsEJpgb3iIOpKWHfq4gROOILNhR37BTvdkVz+5VTgo4qP9oc3te72Va3ZhKLXgVTpP
  template:
    metadata:
      creationTimestamp: null
      name: loki
      namespace: telemetry

