---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oauth2-proxy
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
