---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elastic
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.7.0