---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:*
spec:
  releaseName: oauth2-proxy
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: oauth2-proxy
    version: 3.1.0
  values:
    config:
      existingSecret: oauth2-proxy
      configFile: |-
        email_domains = [ "6f.io" ]
        upstreams = [ "file:///dev/null" ]
    extraArgs:
      provider: google
      skip-provider-button: true
      exclude-logging-paths: /ping
      whitelist-domain: .6f.io
      cookie-domain: .6f.io
      set-authorization-header: true
      set-xauthrequest: true
      reverse-proxy: true
      pass-user-headers: true
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: latest-armv6
    ingress:
      enabled: true
      hosts:
      - sso.6f.io
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
          grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      tls:
      - hosts:
        - sso.6f.io
        secretName: oauth2-proxy-tls
    podAnnotations:
      linkerd.io/inject: enabled
