---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: root
  namespace: root-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
