---
apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: thanos
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  - name: http
    port: 80
    targetPort: http
  selector:
    app: store
