---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: v1.3.0
  values:
    git:
      url: git@github.com:uhthomas/k8s
      path: clusters/k8s-1-17-5-do-0-lon1-1590534650926
    syncGarbageCollection:
      enabled: true
    logFormat: json