---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.4.0
  values:
    controller:
      config:
        proxy-buffers-number: 8
        proxy-buffer-size: 16k
      autoscaling:
        enabled: true
      publishService:
        enabled: true
      service:
        externalTrafficPolicy: Local
    tcp:
      25565: production/minecraft-minecraft:25565
