---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: root
  namespace: root
spec:
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: root
  template:
    metadata:
      labels:
        app: root
    spec:
      containers:
      - name: root
        # v1.3.2
        image: ghcr.io/uhthomas/6f.io@sha256:3ddf7b2d80f53fdef765b6b97dbbaf958d04f87423cc732e9cdc15e564f1ba88
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 2Mi
            cpu: 2m
          limits:
            memory: 8Mi
            cpu: 5m
      imagePullSecrets:
      - name: regcred
