---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: root
  namespace: root
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
