---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: telemetry
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: fluent-bit
  chart:
    repository: https://grafana.github.io/loki/charts
    name: fluent-bit
    version: 0.1.3
  values:
    loki:
      serviceName: loki
