---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: telemetry
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: jaeger-operator
  chart:
    repository: https://jaegertracing.github.io/helm-charts
    name: jaeger-operator
    version: 2.15.0
  values:
    jaeger:
      create: true
