---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: jaeger
spec:
  releaseName: jaeger-operator
  chart:
    repository: https://jaegertracing.github.io/helm-charts
    name: jaeger-operator
    version: v1.3.0
  values:
    jaeger:
      create: true