---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kipp
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kipp
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75