---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: query-frontend
  namespace: thanos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: query-frontend
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
