---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: linkerd2
  namespace: linkerd2
spec:
  releaseName: linkerd2
  chart:
    repository: https://helm.linkerd.io/stable
    name: linkerd2
    version: v2.7.1