---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kipp
  namespace: kipp-dev
spec:
  encryptedData:
    aws-config: AgCTV4At8jLP9P0Bpt6BjxBCZrf3TY3QRG8OWspPSUyvrl1xAfHWy1VGafHREP2dMWNE6jSKZ1+i/urPAEyYH4KxP0Za/Uf/dpGONnqeDxUiIWhPasiwQuyllFNGy2DsAcKa6XHAIXMdXcXyiDHsT37QPzkcYX9s6wk2GBqFnnnuCOqklajRIwVChbJvNMif4FXdVhKhlgpqBqHQN6pkRoATMeWSbN4GSlknNge01awLrCavB3XhR3/1jgctg80+/+UbEQJecC7CmIYoadXNfBLrn89SwuNTckduHulSMiLVVqlzutoufYQk7Uz39KTCehc2tGXH15xR5NaJKGtOH7in00JQ995cAAwCsOHnN9RF/S8nY7fDTFH3nZAqQG6ddRluGS4kVw5zFTkbULBb+Zhe0MgTLEA9A4zrvuWEAOTJc7tdngip9v3witJOQzWn32ZRX+XVECxPV93s5WuI5RQi2+CqOIVjsN8RzMhIjLtwxgW5zHr7oUIi4Vk0xczk/wyDZUdxDwR8K8alDvnd+n29y9lQIUCUbJJ4yqjmIi+Y/baS1/fIs/cxdst7jhnHeg17nAV0mhccEteLlRu+gOamDL53D3b8VEKCLt+ArNZ8k1okbI0cNuSKNGlko4sTahkJIVlMUPibA4pwfH8kw1kGFi/mTY3IwUhXxyJm+HaRAxOTjqbeyt+7BfaGBT+L9pnw7bD0jFseS7V5yzrYKogUo0Q/Qg+Y3/3ppzSSr3Q1c6RfFIoq489rsYXjusGKpJOvm6F+Az1PmjwutO/kCAS1NoLLuI3LS7YO1gzrWVfu+gZ+z7ohHZfmBiibQQX1STbdgVco9wFioKjVJBFoojrl
    database: AgCQr09JJ2Q+lvq/a5rMgStVy+mxufDnJOAc6PcY9v4iG6rFv96+MJxlRZhv2KP+hgj9DjZeZ/AvwoVLuIFegOPag9MPkzEWLocWIit38gdaDREClg3PibwpWMk3XeDmW/cZIIue5UmMl9dBigY2HC28M1v9iv7cnVuS/8DCGRP3FCLdU5DS7SK5nwVjoCt+BXvkY5l8rRIwz7+1EddcjTjMOt+tQOC7dVfRlcPcV22tfOWe/vP5JjttYX2I5bjKcJEdOivwocAwS0LKBXllEuNm4pvzpdz6hoRLJJpdDFtRaXaMWlkRalBxTA8ilxREU7qFy8uwhqKwbY4jSFe/IslPit3eEsGENiHklQYG1Ba2K2tVuIM2s50HfC74Vg09RSNVBBPmH4pfFxNW3Rv13DGiXxl0fGWSftzc/Ugk3d+SPR8cmQWCPz/tMp3rZR+7fll0m+Kwfr6KZGZlJQjBiuMxg8taHF5A0tKDaT0H77qWf21G//Nj2X6ZlCjZTecxYjEnMDZwM521eQuVUVzwA/0WZo+3YTwzh9f7XSKJ98am+ZcEdaAhlS7elc53VNJ9ucre6oy4jSuJ0OREHPsH9TKcShy0DL0HOG5PhrJQZ+a2iubv0/tm0p6B/Av2WdrnFvNgu+KnoluZnbCHHh3i2hZhdRXgHX/g0ZFlwwOlODvhg0RXF321LhGtEoj+ycYDGiCUwtbukPYzW0osKqCxuSwKBX3ku3Bh16UVJdAFZkJyLd6sCBkfpu98zso+VX8aX6T0bHQChgp8NP8fjKjyR0RlCdhzZ6OhyGc+Zicf/8I2GwYULA==
  template:
    metadata:
      name: kipp
      namespace: kipp-dev
    type: Opaque
