---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: grafana
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem