apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgCAVKQ3n0Rp0aGkTg6i+iHw0VDbGekkDl3JCKAlAMksc1miYdMtr49GLqnnmeSnQkbx08BphnnMusY2UQGoOfhOrpF4FWQkO1LKTGYFpGGLM+cLikzUGt51phM5LQG+thSEnfsZkJQ7siWGKFNc7Sbv79Ck7zZ1Li+ZKYQumKjxEVBQVL7CUOyAIUT3rGMjliiMi3COkn4z2t85asPamJPsIAEGPywMPGA1H+KUszHLKLtAebtY0K68kyL3YeSTBWda8E2WNtWloBCZf5bef5gISf56ffMq/Ym5Sr3ok9WrEbcLbRHLXU+ykcPyhKXZ0+fkvk25/uBdw/b9rIgaXXrxF5NZwNuHHmM1Umo8sWZg0Wck9jpPUIXNIT0Wu9RxaTxploR814kkROf4sOYWxXjDIP9tb43nS1RU9E+wVnhf0vmoODc/GaBukfpIt7seOs6OVMpmuv/ybh2GOhIguV5Zipp5hVNSjgNIUOUgyCHB+vl5Ouy/O7vN6s+x0bk6wpCmpHW7Nn23BVwJmxCaM1J9gs4tto7LCz4BZ6w+1nhZQuSIlgS1Ns9ZLlWUFS5+NN8d33TenlIBUhN728RmbDwQm489gOQfEHjZPR3NLuL+6r0E52g4IrY0JgFeO2yPLmjBhaZpu4UHhsfv8lFUucIuNxGD8AkAaLyEB1UdYMfbM1/Q3YA+qtmaG0GpSODTF6SJfMWxK+GEPbBHEdS1+QjbRGr2hZx1vGnRAOCi7fSuJ04oebQAkzuDjSTjsOS7R3kWg2Xgg8LfDQwszXl0pzaif3SqNxJGqD0DMcxUXq2hucriNjmA3KKi/bqc6ewwBBfPzQBW2o5QN4YL2pW3LCsuzVR2T7gQyd71/IXluYinGTcRIsYesfcY8m2rSxTjOAVw7PfD60IijmGZ0amVHCPF77tMgkGBC3FxorOwR/5gEsj6zVX9JIfphEwSl6et7/8eANBxZrAXNUc/a5vROj+7oag=
  template:
    metadata:
      name: regcred
      namespace: production
    type: kubernetes.io/dockerconfigjson

