---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sfc
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sfc
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
