---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: telemetry
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: 13.1.0
  values:
    podSecurityPolicy:
      enabled: true
    kubeStateMetrics:
      enabled: false
    server:
      strategy:
        type: Recreate
      retention: 1y
      replicaCount: 2
      global:
        scrape_interval: 15s
      extraFlags:
      - web.enable-lifecycle
      - storage.tsdb.min-block-duration=2h
      - storage.tsdb.max-block-duration=2h
      sidecarContainers:
      - name: thanos-sidecar
        # v0.18.0
        image: quay.io/thanos/thanos@sha256:b94171aed499b2f1f81b6d3d385e0eeeca885044c59cef28ce6a9a9e8a827217
        args:
        - sidecar
        - --tsdb.path=/data
        - --prometheus.url=http://127.0.0.1:9090
        - --objstore.config-file=/etc/secret/objstore.yaml
        - --reloader.config-file=/etc/config/prometheus.yaml
        - --shipper.upload-compacted
        ports:
        - name: thanos-http
          containerPort: 81
        - name: thanos-grpc
          containerPort: 50051
        volumeMounts:
        - name: storage-volume
          mountPath: /data
        - name: thanos
          mountPath: /etc/secret
          readOnly: true
        - name: config-volume
          mountPath: /etc/config
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: thanos-http
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /-/ready
            port: thanos-http
          initialDelaySeconds: 5
          periodSeconds: 3
      extraVolumes:
      - name: share
        emptyDir: {}
      extraVolumeMounts:
      - name: share
        mountPath: /etc/share
      extraSecretMounts:
      - name: thanos
        mountPath: /etc/secret
        secretName: thanos
