---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logzio-logs-secret
  namespace: fluentd
spec:
  encryptedData:
    logzio-log-shipping-token: AgAQuI7i5IOHjOj7EP6qtVQkwXQTHdx3sRCwCcxgxryrac1xPb8KYHeI5KpnLwtDRdP63jaNLza+Vp7Qy7Zi1LzCHtk6KuPMxU9SZC9J8Yxnxci6mTl5dc/LRzAWmoRqlIgXVE8kethThujWPtacnzwwH/vgPZ6p3TyPis07aHrdMvuCScPKvA8eW5xgSccXF1FZ9wffl5XVSYkK4aJ/CoWHODz5EuxIuBWswnRhwJU00duaX5g6DPkGkF6uH95o+PgVx5diokso9f7XrYmwh+D0cybqcsOGpAs+PNFtu0b+2/iUTYXI7wuFdZGk+PQm1Ttwm4jBb9o+ZREPnM+YsUJMkgdHQ0O8uD5XMj1qDG24Davtpw3zX4zPhKzAVLRDe+w48Ra4WxAFitlA/Jh32CZAr2luxMWoIesAYzXjxkHnApGTec8mPUzEaAGK4AJLLSJ0yXftUjR+37CuNR4d3kZNjtScmYpn35XgdA/66Q5kaBoKeS9z8snK3I/2NCuEUcv4Sc1GlwXFyXzpDJ24fQ+z6GdD4fZkciAVGX8p9ecGrIL4e37DiKXA7hj16DsT6N16yOevcZc2z6DIg7d2Aw3e5U1oMBYOHwREqgn3dLJoX/XUi2NuOzcOxC/s6aLzkZCcH6wuHQP/b1B/A7iba0QdiquOfOXmSr9BBPaEs2navvIWvkL15FR436cYgXMH4FL7bUHW3O8YJDWx/+OlkoOHUTHjTymp/7K0ZYf+reVLCA==
  template:
    metadata:
      name: logzio-logs-secret
      namespace: fluentd