---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector
  namespace: vector
data:
  vector.toml: |
    data_dir = "/var/lib/vector"
    [sources.kubernetes]
      type = "kubernetes"
    [sinks.console]
      type = "console"
      inputs = ["kubernetes"]
    [sinks.out]
      endpoint = "http://loki:3100"
      inputs = ["in"]
      type = "loki"