---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector
  namespace: vector
data:
  vector.toml: |
    data_dir = "/var/lib/vector"
    [sources.kubernetes]
      type = "kubernetes"
    [sinks.out]
      inputs = ["kubernetes"]
      endpoint = "http://loki:3100"
      type = "loki"