---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: vector
  labels:
    app: vector
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccount: vector
      serviceAccountName: vector
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: vector
        image: timberio/vector:0.9.1-alpine
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: vector-config
          mountPath: /etc/vector/vector.toml
          readOnly: true
          subPath: vector.toml
        - name: data
          path: /var/lib/vector
          type: DirectoryOrCreate
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: vector-config
        configMap:
          name: vector