---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kipp
  namespace: dev
spec:
  encryptedData:
    filesystem: AgC+Ia4akwou5A6Sitc6/CgRFEqSWiktPDTqqPCV/QsVGleCuSuw34NWUIyqiFoQYOc+JwOig6PpOZbdbg0PIqAP2hywkkrb9l9mkXKwESM9zk0dBRGQCLnewDCAWQqd5BOP3tLTO+bYk4P9tc3rIYWBLYo6vHf1r5oWMpk0FdZUp9Iv6F9d8uE32+XqMQ4KeJb/30v3urcFjKcpGhugYIokmTG6MDppTkDZV4eofQ2IKIWMFvDlpX8VxWJwkL4cCy55/c6EXjYNuwR3GeL9l5OUO878Vwx6cXbjMwj8Rb2q6EbhAkquXpJ7U4AOxCyTr8UYrKCyhuHiAh5L2ZA/c+jKBh/Uqg+Q6gY+m6pHu40E/b3UP4bFJZqDYxd/yVmtMemJxI6l0yCdJ27GDypJkyJZxo1ZDTjJFFbkCHjbARESPtc3d0E2xjs62lDmSTvOfcjdf+oGbjmPAFnMYkTpDLJCGtIIrk9ij5JL7KirPjJN9PKjfRqjYhqJlPxcJev8DI2yUuaKkycr5XI5JWHkpLvIdd8eXQcfwBEUE4IjntBOp+lP263aEcWK3gl9Qp3dIWsMlvIAC7ZUfy7/fSv0M8RknSRJiew5NHe9yn9vVRYudWgRoXxQg01uPepYYO9r0VANIPmpcJidFaiQhLsDm6ZfD24Kbfk2EaDIuB13hh4lnxfDNbB7C1x1G16xONbT0FrvxlhFRFzIBsDtnkUQ8hDTdOQ81S12nLNLvM4YgDkX475JWCyd3so0PB4Mj1w7BIqYpbGeE3CRa1hjvlCFS3WkWT+HZgD3M0hYFQRtUkU0x/kv9ba7RgQ3HeEPS2gz5ejhyTzSc86mmXjb97KpJbZ9vxSB9qNmF1oibhJY
  template:
    metadata:
      name: kipp
      namespace: dev