name: Push
on:
  push:
    branches:
    - master
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/setup-kubectl@v1
    - uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}
        k8s-secret: ${{ secrets.K8S_SECRET }}
    - run: |
        k apply -f clusters/desire -R --dry-run=client -ojson \
        | jq '.items[].metadata.labels."app.kubernetes.io/managed-by" = "git-manifests"' \
        | k apply -f - -l app.kubernetes.io/managed=git-manifests
