name: Bazel
on:
  push:
    branches: [main]
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bazelisk
      run: curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64" | install -D /dev/stdin "${GITHUB_WORKSPACE}/bin/bazel"
    - run: bazel build //...
    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    # https://github.com/bazelbuild/rules_k8s/issues/640
    - run: bazel run //clusters/mahalo:object.apply -- --prune
