name: Colmena
on:
  push:
    branches: [main]
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_ed25519
        known_hosts: unnecessary
        config: |
          Host *
            ControlMaster auto
            ControlPath ~/.ssh/sockets/%r@%h-%p
            ControlPersist 600
    - run: mkdir -p ~/.ssh/sockets
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: starjunk
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - uses: tailscale/github-action@main
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - run: nix-shell --run "colmena apply -f nix/hive.nix"
