name: Colmena
on:
  push:
    branches: [main]
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_ed25519
        config: |
          Host *
            ControlMaster auto
            ControlPath ~/.ssh/sockets/%r@%h-%p
            ControlPersist 600
    - run: mkdir -p ~/.ssh/sockets
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install Colmena
      run: nix-env -f https://github.com/zhaofengli/colmena/archive/main.tar.gz -i
    - uses: tailscale/github-action@main
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - run: colmena apply -f nix/hive.nix
