name: k8s-diff
on: [pull_request]
jobs:
  base:
    name: Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build
        run: |
          bazel build \
          --config=ci \
          --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
          //k8s/unwind:list
      - name: Get output path
        id: get-output-path
        run: echo "PATH=$(bazel cquery --output=files //k8s/unwind:list 2> /dev/null)" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v3
        with:
          name: base
          path: "${{ steps.get-output-path.outputs.PATH }}"
  head:
    name: Head
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build
        run: |
          bazel build \
          --config=ci \
          --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
          //k8s/unwind:list
      - name: Get output path
        id: get-output-path
        run: echo "PATH=$(bazel cquery --output=files //k8s/unwind:list 2> /dev/null)" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v3
        with:
          name: head
          path: "${{ steps.get-output-path.outputs.PATH }}"
  compare:
    name: Compare
    needs: [base, head]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g json-diff
      - name: Comment diff on PR
        uses: actions/github-script@v6
        with:
          script: |
            const { diffString } = require('json-diff')

            const baseList = require ('./head/list.json')
            const headList = require('./head/list.json')

            const diff = diffString(baseList, headList)

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `\`\`\`diff\n${diff}\n\`\`\``
            })
