name: k8s
on:
  push:
    branches: [main]
jobs:
  unwind:
    name: Unwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.40.0"
      - name: Login to the Kubernetes cluster
        run: tailscale configure kubeconfig tailscale-operator
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      # https://github.com/bazelbuild/rules_k8s/issues/640
      # TODO: use --prune
      - name: Apply
        run: |
          bazel run \
          --config=ci \
          --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }} \
          //k8s/unwind:object.apply
