name: Validate
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      KUBERNETES_VERSION: 1.17.5
    steps:
      - uses: actions/checkout@master
      - name: Validate Helm Releases
        uses: stefanprodan/hrval-action@9dce45ff21910cc28b28b8504fcd68aeb18f1e8c
        with:
          helmRelease: .
          helmVersion: v3
          kubernetesVersion: ${{ env.KUBERNETES_VERSION }}
      - name: Validate k8s manifests
        uses: instrumenta/kubeval-action@master
        with:
          version: ${{ env.KUBERNETES_VERSION }}