apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kipp-filesystem
  namespace: default
spec:
  encryptedData:
    url: AgAnUonNH8GD8Up/+VUjrBCgRx/HBwsD8HytJ7U9gqyovsB1e11geNCeeP1MBOPYG4FNygMtnCq1rRsiQ2JGqMPUOsi2TtbRYHGR3ojHisW4eGPGZMmt6dxC9Zq5o2tK4gPpg1SEPIixm1A8xRzY7VbBwCRxsB/Es/6Qkns/+RDGmXSH0tR+EsgMconaFBMsCym2Ga7gz8QCXuiveFipPF/9sM89N91oVg7g0U6/c6DkRvAUuCZU6mAPKMGO8SkvA2saYFUu6UYIZjBw5XsSp0G4xhzJWBcRmdI2KqtohjwW7BIWn4mUVhIPqwSMy4ukcEQfYOgP2x7tc03PX5RWIOOd/YFhd3qu1EG7lrS0CEBIUda69wkSmf//EIbVe6LI10KzcI4R7fDCJYz8qjiTYpvSNOHN7i/e0LYLJxGSr8rDM0Jv7GfbDtorgTFQ21gcOkMd89aNCb8GCW4P/SLKlAii2b9F44WAaJEnEu5XViUrLTZ18cgN4irTOTIuRnbyTlPtcrSLu+LgqL+WCb9yx1V9iM3rA3m2DA5gFofXsmnorQ5mhEXV0iPgEsoWAaiTcAM13P/NYEPCmk58GMANl1nDoY+WcpiDOzFPihW3ef1X7gzX4W8U/BYnwH+xo0/0tVqB6ndx0NpzjQGNEN8iGRtY5hwIe/m9PHFEtAZ615YHepGZJBWQ3pY8Mv+IbCfWogu3q4bp8H3C+exqs+xoICwlJVSGDpLAkzP5m/3yO4CLB5lFraYjBGWy1djVnRPY1El9bwAeYrNhE8asVXftWj2k7F1p0NgCD8djeg8C/YMd4OfpqC3Y3TurwhRcodyZfroK5LzlGN6iRFbg6FYxR7+1IPSWWcHcOvkULzeKLA==
  template:
    metadata:
      name: kipp-filesystem
      namespace: default